// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadDotenv } from "dotenv";

// A DATABASE_URL already exported in the shell (e.g. `export DATABASE_URL=...`
// before running this) always wins — used for one-off migration runs where
// the value should never be written to a file.
const shellDatabaseUrl = process.env.DATABASE_URL || undefined;

loadDotenv(); // .env
// .env.local mirrors Next.js's own precedence (loaded after .env, wins on
// conflicts) — this is where `vercel env pull` writes real per-environment
// secrets (e.g. DATABASE_URL from the Neon integration) without them ever
// needing to live in the committed .env template.
loadDotenv({ path: ".env.local", override: true });

if (shellDatabaseUrl) process.env.DATABASE_URL = shellDatabaseUrl;

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
