// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// .env.local mirrors Next.js's own precedence (loaded after .env, wins on
// conflicts) — this is where `vercel env pull` writes real per-environment
// secrets (e.g. DATABASE_URL from the Neon integration) without them ever
// needing to live in the committed .env template.
import { config as loadDotenv } from "dotenv";
loadDotenv({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
